# Generated by Django 4.2.6 on 2023-11-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollhours',
            name='minutes',
            field=models.IntegerField(blank=True, help_text='Set to Timedelta (hours, minutes) ending_time - starting_time', null=True),
        ),
    ]
