# Generated by Django 4.2.6 on 2023-11-06 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0004_alter_payrollhours_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrollhours',
            options={'ordering': ['date_worked', 'starting_time']},
        ),
        migrations.RemoveField(
            model_name='payrollhours',
            name='entry_date',
        ),
        migrations.AddField(
            model_name='payrollhours',
            name='date_worked',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='payrollhours',
            name='employee_submitted',
            field=models.BooleanField(default=False, help_text='Employee must review the entry and check submit box'),
        ),
        migrations.AlterField(
            model_name='payrollhours',
            name='starting_time',
            field=models.TimeField(help_text='Starting Time for date_worked'),
        ),
    ]
