# Generated by Django 4.2.6 on 2023-11-06 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0006_alter_payrollhours_date_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollhours',
            name='date_worked',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
