# Generated by Django 4.2.6 on 2023-11-13 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0007_alter_payrollhours_date_worked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollhours',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='timecard.period'),
        ),
    ]
