# Generated by Django 4.2.6 on 2023-11-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0008_alter_payrollhours_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeuser',
            name='vacation_hours',
            field=models.IntegerField(default=0, help_text='Vacation hours alloted per year'),
        ),
        migrations.AlterField(
            model_name='payrollhours',
            name='date_worked',
            field=models.DateField(default='11/19/2023'),
        ),
    ]
