# Generated by Django 4.2.6 on 2023-11-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecard', '0009_activeuser_vacation_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollhours',
            name='adjustment_hours',
        ),
        migrations.AddField(
            model_name='payrollhours',
            name='adjustment_mins',
            field=models.IntegerField(default=0, help_text='Adjustment to minutes from previous month'),
        ),
        migrations.AlterField(
            model_name='payrollhours',
            name='date_worked',
            field=models.DateField(default='11/20/2023'),
        ),
    ]
